spring:
  datasource:
    url: jdbc:mysql://182.61.133.118:3306/spring-boot-demo
    username: root
    password: newtalent
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf8
        # 这个必须要加，否则 Activiti 自动建表会失败
        nullCatalogMeansCurrent: true
  activiti:
    history-level: full
    db-history-used: true